/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interfaz.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
gestion_usuario_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		datosValidar autenticar_usuario_1_arg;
		proxNodo registrarusuario_1_arg;
		datosValidar eliminar_usuario_1_arg;
		proxNodo modificar_usuario_1_arg;
		datosValidar consultarusuario_1_arg;
		int repartir_fichas_1_arg;
		int enviar_jugada_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case autenticar_usuario:
		_xdr_argument = (xdrproc_t) xdr_datosValidar;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) autenticar_usuario_1_svc;
		break;

	case registrarUsuario:
		_xdr_argument = (xdrproc_t) xdr_proxNodo;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) registrarusuario_1_svc;
		break;

	case listarUsuarios:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_proxNodo;
		local = (char *(*)(char *, struct svc_req *)) listarusuarios_1_svc;
		break;

	case eliminar_Usuario:
		_xdr_argument = (xdrproc_t) xdr_datosValidar;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) eliminar_usuario_1_svc;
		break;

	case modificar_usuario:
		_xdr_argument = (xdrproc_t) xdr_proxNodo;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) modificar_usuario_1_svc;
		break;

	case consultarUsuario:
		_xdr_argument = (xdrproc_t) xdr_datosValidar;
		_xdr_result = (xdrproc_t) xdr_nodo_usuario;
		local = (char *(*)(char *, struct svc_req *)) consultarusuario_1_svc;
		break;

	case repartir_fichas:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_fichas;
		local = (char *(*)(char *, struct svc_req *)) repartir_fichas_1_svc;
		break;

	case empezar_partida:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_fichas;
		local = (char *(*)(char *, struct svc_req *)) empezar_partida_1_svc;
		break;

	case enviar_jugada:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_fichas;
		local = (char *(*)(char *, struct svc_req *)) enviar_jugada_1_svc;
		break;

	case estado_tablero:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_fichas;
		local = (char *(*)(char *, struct svc_req *)) estado_tablero_1_svc;
		break;

	case estado_cliente:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_fichas;
		local = (char *(*)(char *, struct svc_req *)) estado_cliente_1_svc;
		break;

	case contar_puntos:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) contar_puntos_1_svc;
		break;

	case consultar_estadisticas:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) consultar_estadisticas_1_svc;
		break;

	case salir:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) salir_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (gestion_usuario, gestion_usuario_version);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, gestion_usuario, gestion_usuario_version, gestion_usuario_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (gestion_usuario, gestion_usuario_version, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, gestion_usuario, gestion_usuario_version, gestion_usuario_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (gestion_usuario, gestion_usuario_version, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
