/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interfaz.h"

bool_t *
autenticar_usuario_1_svc(datosValidar *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
registrarusuario_1_svc(proxNodo *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

proxNodo *
listarusuarios_1_svc(void *argp, struct svc_req *rqstp)
{
	static proxNodo  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
eliminar_usuario_1_svc(datosValidar *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
modificar_usuario_1_svc(proxNodo *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

nodo_usuario *
consultarusuario_1_svc(datosValidar *argp, struct svc_req *rqstp)
{
	static nodo_usuario  result;

	/*
	 * insert server code here
	 */

	return &result;
}

fichas *
repartir_fichas_1_svc(int *argp, struct svc_req *rqstp)
{
	static fichas  result;

	/*
	 * insert server code here
	 */

	return &result;
}

fichas *
enviar_jugada_1_svc(int *argp, struct svc_req *rqstp)
{
	static fichas  result;

	/*
	 * insert server code here
	 */

	return &result;
}

fichas *
estado_tablero_1_svc(void *argp, struct svc_req *rqstp)
{
	static fichas  result;

	/*
	 * insert server code here
	 */

	return &result;
}

fichas *
empezar_partida_1_svc(void *argp, struct svc_req *rqstp)
{
	static fichas  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
consultar_estadisticas_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
salir_1_svc(void *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}
