package sop_corba;


/**
* sop_corba/_Interfaz_AdministradorStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* sábado 10 de junio de 2017 12:13:27 PM COT
*/

public class _Interfaz_AdministradorStub extends org.omg.CORBA.portable.ObjectImpl implements sop_corba.Interfaz_Administrador
{

  public boolean suscribir_Usuario (sop_corba.usuarioCallbackInt objcllbck, String loginUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("suscribir_Usuario", true);
                sop_corba.usuarioCallbackIntHelper.write ($out, objcllbck);
                $out.write_string (loginUsuario);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return suscribir_Usuario (objcllbck, loginUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // suscribir_Usuario

  public boolean eliminarSuscripcion_Usuario (String loginUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarSuscripcion_Usuario", true);
                $out.write_string (loginUsuario);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarSuscripcion_Usuario (loginUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarSuscripcion_Usuario

  public String[] obtenerSuscritos ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("obtenerSuscritos", true);
                $in = _invoke ($out);
                String $result[] = sop_corba.Interfaz_AdministradorPackage.ListUsuariosSuscritosHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return obtenerSuscritos (        );
            } finally {
                _releaseReply ($in);
            }
  } // obtenerSuscritos

  public void notificarUsuarios (String mensaje)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("notificarUsuarios", true);
                $out.write_string (mensaje);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                notificarUsuarios (mensaje        );
            } finally {
                _releaseReply ($in);
            }
  } // notificarUsuarios

  public void AceptarPaquetes (String loginUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("AceptarPaquetes", true);
                $out.write_string (loginUsuario);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                AceptarPaquetes (loginUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // AceptarPaquetes

  public boolean seleccionarAudio (String ruta)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("seleccionarAudio", true);
                $out.write_string (ruta);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return seleccionarAudio (ruta        );
            } finally {
                _releaseReply ($in);
            }
  } // seleccionarAudio

  public void EjecutarAudio ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("EjecutarAudio", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                EjecutarAudio (        );
            } finally {
                _releaseReply ($in);
            }
  } // EjecutarAudio

  public void enviarAudio (String loginUsuario, byte[] paquete)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("enviarAudio", true);
                $out.write_string (loginUsuario);
                sop_corba.Interfaz_AdministradorPackage.audioHelper.write ($out, paquete);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                enviarAudio (loginUsuario, paquete        );
            } finally {
                _releaseReply ($in);
            }
  } // enviarAudio

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/Interfaz_Administrador:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _Interfaz_AdministradorStub
