package sop_corba;


/**
* sop_corba/_usuarioCallbackIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* sábado 10 de junio de 2017 12:13:27 PM COT
*/

public class _usuarioCallbackIntStub extends org.omg.CORBA.portable.ObjectImpl implements sop_corba.usuarioCallbackInt
{

  public void actualizarSuscritos (String[] ListUsuariosSuscritos)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarSuscritos", true);
                sop_corba.usuarioCallbackIntPackage.ListUsuariosSuscritosHelper.write ($out, ListUsuariosSuscritos);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                actualizarSuscritos (ListUsuariosSuscritos        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarSuscritos

  public boolean resibirMensaje (String mensaje)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("resibirMensaje", true);
                $out.write_string (mensaje);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return resibirMensaje (mensaje        );
            } finally {
                _releaseReply ($in);
            }
  } // resibirMensaje

  public void resibirAudio (byte[] paquete)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("resibirAudio", true);
                sop_corba.usuarioCallbackIntPackage.audioHelper.write ($out, paquete);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                resibirAudio (paquete        );
            } finally {
                _releaseReply ($in);
            }
  } // resibirAudio

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/usuarioCallbackInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _usuarioCallbackIntStub
