package sop_corba;


/**
* sop_corba/autenticacionUsuarioPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* sábado 10 de junio de 2017 12:13:27 PM COT
*/

public class autenticacionUsuarioPOATie extends autenticacionUsuarioPOA
{

  // Constructors

  public autenticacionUsuarioPOATie ( sop_corba.autenticacionUsuarioOperations delegate ) {
      this._impl = delegate;
  }
  public autenticacionUsuarioPOATie ( sop_corba.autenticacionUsuarioOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public sop_corba.autenticacionUsuarioOperations _delegate() {
      return this._impl;
  }
  public void _delegate (sop_corba.autenticacionUsuarioOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean ingresar (String login, String clave)
  {
    return _impl.ingresar(login, clave);
  } // ingresar

  public String[] obtenerUsuariosActivos ()
  {
    return _impl.obtenerUsuariosActivos();
  } // obtenerUsuariosActivos

  public boolean salir (String login)
  {
    return _impl.salir(login);
  } // salir

  private sop_corba.autenticacionUsuarioOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class autenticacionUsuarioPOATie
