package sop_corba;


/**
* sop_corba/autenticacionUsuario.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* martes 6 de junio de 2017 10:16:52 AM COT
*/

public interface autenticacionUsuario extends autenticacionUsuarioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface autenticacionUsuario
