package sop_corba;


/**
* sop_corba/autenticacionUsuarioPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* sábado 10 de junio de 2017 12:13:27 PM COT
*/

public abstract class autenticacionUsuarioPOA extends org.omg.PortableServer.Servant
 implements sop_corba.autenticacionUsuarioOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ingresar", new java.lang.Integer (0));
    _methods.put ("obtenerUsuariosActivos", new java.lang.Integer (1));
    _methods.put ("salir", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/autenticacionUsuario/ingresar
       {
         String login = in.read_string ();
         String clave = in.read_string ();
         boolean $result = false;
         $result = this.ingresar (login, clave);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // sop_corba/autenticacionUsuario/obtenerUsuariosActivos
       {
         String $result[] = null;
         $result = this.obtenerUsuariosActivos ();
         out = $rh.createReply();
         sop_corba.autenticacionUsuarioPackage.usuariosActivosHelper.write (out, $result);
         break;
       }

       case 2:  // sop_corba/autenticacionUsuario/salir
       {
         String login = in.read_string ();
         boolean $result = false;
         $result = this.salir (login);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/autenticacionUsuario:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public autenticacionUsuario _this() 
  {
    return autenticacionUsuarioHelper.narrow(
    super._this_object());
  }

  public autenticacionUsuario _this(org.omg.CORBA.ORB orb) 
  {
    return autenticacionUsuarioHelper.narrow(
    super._this_object(orb));
  }


} // class autenticacionUsuarioPOA
