package sop_corba;

/**
* sop_corba/Interfaz_GestionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* martes 6 de junio de 2017 10:16:52 AM COT
*/

public final class Interfaz_GestionHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.Interfaz_Gestion value = null;

  public Interfaz_GestionHolder ()
  {
  }

  public Interfaz_GestionHolder (sop_corba.Interfaz_Gestion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.Interfaz_GestionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.Interfaz_GestionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.Interfaz_GestionHelper.type ();
  }

}
