package sop_corba;


/**
* sop_corba/Interfaz_GestionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* sábado 10 de junio de 2017 12:13:27 PM COT
*/

public abstract class Interfaz_GestionPOA extends org.omg.PortableServer.Servant
 implements sop_corba.Interfaz_GestionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registrarUsuario", new java.lang.Integer (0));
    _methods.put ("consultarUsuarios", new java.lang.Integer (1));
    _methods.put ("consultarUsuario", new java.lang.Integer (2));
    _methods.put ("exiteUsuario", new java.lang.Integer (3));
    _methods.put ("actualizarUsuario", new java.lang.Integer (4));
    _methods.put ("eliminarUsuario", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/Interfaz_Gestion/registrarUsuario
       {
         sop_corba.Usuario N_Usuario = sop_corba.UsuarioHelper.read (in);
         boolean $result = false;
         $result = this.registrarUsuario (N_Usuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // sop_corba/Interfaz_Gestion/consultarUsuarios
       {
         sop_corba.Usuario $result[] = null;
         $result = this.consultarUsuarios ();
         out = $rh.createReply();
         sop_corba.Interfaz_GestionPackage.ListUsuariosHelper.write (out, $result);
         break;
       }

       case 2:  // sop_corba/Interfaz_Gestion/consultarUsuario
       {
         String login = in.read_string ();
         sop_corba.Usuario $result = null;
         $result = this.consultarUsuario (login);
         out = $rh.createReply();
         sop_corba.UsuarioHelper.write (out, $result);
         break;
       }

       case 3:  // sop_corba/Interfaz_Gestion/exiteUsuario
       {
         String login = in.read_string ();
         boolean $result = false;
         $result = this.exiteUsuario (login);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // sop_corba/Interfaz_Gestion/actualizarUsuario
       {
         sop_corba.Usuario objUsuario = sop_corba.UsuarioHelper.read (in);
         String login = in.read_string ();
         boolean $result = false;
         $result = this.actualizarUsuario (objUsuario, login);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // sop_corba/Interfaz_Gestion/eliminarUsuario
       {
         String login = in.read_string ();
         boolean $result = false;
         $result = this.eliminarUsuario (login);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/Interfaz_Gestion:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Interfaz_Gestion _this() 
  {
    return Interfaz_GestionHelper.narrow(
    super._this_object());
  }

  public Interfaz_Gestion _this(org.omg.CORBA.ORB orb) 
  {
    return Interfaz_GestionHelper.narrow(
    super._this_object(orb));
  }


} // class Interfaz_GestionPOA
