package sop_corba;


/**
* sop_corba/Interfaz_AdministradorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* martes 6 de junio de 2017 10:16:52 AM COT
*/

public abstract class Interfaz_AdministradorPOA extends org.omg.PortableServer.Servant
 implements sop_corba.Interfaz_AdministradorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("suscribir_Usuario", new java.lang.Integer (0));
    _methods.put ("eliminarSuscripcion_Usuario", new java.lang.Integer (1));
    _methods.put ("obtenerSuscritos", new java.lang.Integer (2));
    _methods.put ("notificarUsuario", new java.lang.Integer (3));
    _methods.put ("seleccionarAudio", new java.lang.Integer (4));
    _methods.put ("EjecutarAudio", new java.lang.Integer (5));
    _methods.put ("enviarAudio", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/Interfaz_Administrador/suscribir_Usuario
       {
         sop_corba.usuarioCallbackInt objcllbck = sop_corba.usuarioCallbackIntHelper.read (in);
         String loginUsuario = in.read_string ();
         boolean $result = false;
         $result = this.suscribir_Usuario (objcllbck, loginUsuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // sop_corba/Interfaz_Administrador/eliminarSuscripcion_Usuario
       {
         String loginUsuario = in.read_string ();
         boolean $result = false;
         $result = this.eliminarSuscripcion_Usuario (loginUsuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // sop_corba/Interfaz_Administrador/obtenerSuscritos
       {
         String $result[] = null;
         $result = this.obtenerSuscritos ();
         out = $rh.createReply();
         sop_corba.Interfaz_AdministradorPackage.ListUsuariosSuscritosHelper.write (out, $result);
         break;
       }

       case 3:  // sop_corba/Interfaz_Administrador/notificarUsuario
       {
         String loginUsuario = in.read_string ();
         String mensaje = in.read_string ();
         this.notificarUsuario (loginUsuario, mensaje);
         out = $rh.createReply();
         break;
       }

       case 4:  // sop_corba/Interfaz_Administrador/seleccionarAudio
       {
         String ruta = in.read_string ();
         boolean $result = false;
         $result = this.seleccionarAudio (ruta);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // sop_corba/Interfaz_Administrador/EjecutarAudio
       {
         boolean $result = false;
         $result = this.EjecutarAudio ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // sop_corba/Interfaz_Administrador/enviarAudio
       {
         String loginUsuario = in.read_string ();
         byte paquete[] = sop_corba.Interfaz_AdministradorPackage.audioHelper.read (in);
         this.enviarAudio (loginUsuario, paquete);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/Interfaz_Administrador:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Interfaz_Administrador _this() 
  {
    return Interfaz_AdministradorHelper.narrow(
    super._this_object());
  }

  public Interfaz_Administrador _this(org.omg.CORBA.ORB orb) 
  {
    return Interfaz_AdministradorHelper.narrow(
    super._this_object(orb));
  }


} // class Interfaz_AdministradorPOA
