package sop_corba;


/**
* sop_corba/Interfaz_AdministradorPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* martes 6 de junio de 2017 10:16:52 AM COT
*/

public class Interfaz_AdministradorPOATie extends Interfaz_AdministradorPOA
{

  // Constructors

  public Interfaz_AdministradorPOATie ( sop_corba.Interfaz_AdministradorOperations delegate ) {
      this._impl = delegate;
  }
  public Interfaz_AdministradorPOATie ( sop_corba.Interfaz_AdministradorOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public sop_corba.Interfaz_AdministradorOperations _delegate() {
      return this._impl;
  }
  public void _delegate (sop_corba.Interfaz_AdministradorOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean suscribir_Usuario (sop_corba.usuarioCallbackInt objcllbck, String loginUsuario)
  {
    return _impl.suscribir_Usuario(objcllbck, loginUsuario);
  } // suscribir_Usuario

  public boolean eliminarSuscripcion_Usuario (String loginUsuario)
  {
    return _impl.eliminarSuscripcion_Usuario(loginUsuario);
  } // eliminarSuscripcion_Usuario

  public String[] obtenerSuscritos ()
  {
    return _impl.obtenerSuscritos();
  } // obtenerSuscritos

  public void notificarUsuario (String loginUsuario, String mensaje)
  {
    _impl.notificarUsuario(loginUsuario, mensaje);
  } // notificarUsuario

  public boolean seleccionarAudio (String ruta)
  {
    return _impl.seleccionarAudio(ruta);
  } // seleccionarAudio

  public boolean EjecutarAudio ()
  {
    return _impl.EjecutarAudio();
  } // EjecutarAudio

  public void enviarAudio (String loginUsuario, byte[] paquete)
  {
    _impl.enviarAudio(loginUsuario, paquete);
  } // enviarAudio

  private sop_corba.Interfaz_AdministradorOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class Interfaz_AdministradorPOATie
