package sop_corba;


/**
* sop_corba/Interfaz_AdministradorPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* jueves 1 de junio de 2017 11:29:38 AM COT
*/

public class Interfaz_AdministradorPOATie extends Interfaz_AdministradorPOA
{

  // Constructors

  public Interfaz_AdministradorPOATie ( sop_corba.Interfaz_AdministradorOperations delegate ) {
      this._impl = delegate;
  }
  public Interfaz_AdministradorPOATie ( sop_corba.Interfaz_AdministradorOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public sop_corba.Interfaz_AdministradorOperations _delegate() {
      return this._impl;
  }
  public void _delegate (sop_corba.Interfaz_AdministradorOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean ingresoSistemaAdministrador (String login, String clave)
  {
    return _impl.ingresoSistemaAdministrador(login, clave);
  } // ingresoSistemaAdministrador

  public boolean registrarUsuario (sop_corba.Usuario N_Usuario)
  {
    return _impl.registrarUsuario(N_Usuario);
  } // registrarUsuario

  public sop_corba.Usuario[] consultarUsuarios ()
  {
    return _impl.consultarUsuarios();
  } // consultarUsuarios

  public sop_corba.Usuario consultarUsuario (String login)
  {
    return _impl.consultarUsuario(login);
  } // consultarUsuario

  public boolean exiteUsuario (String login)
  {
    return _impl.exiteUsuario(login);
  } // exiteUsuario

  public boolean actualizarUsuario (sop_corba.Usuario objUsuario, String login)
  {
    return _impl.actualizarUsuario(objUsuario, login);
  } // actualizarUsuario

  public boolean eliminarUsuario (String login)
  {
    return _impl.eliminarUsuario(login);
  } // eliminarUsuario

  public boolean seleccionarAudio (String ruta)
  {
    return _impl.seleccionarAudio(ruta);
  } // seleccionarAudio

  public boolean EjecutarAudio ()
  {
    return _impl.EjecutarAudio();
  } // EjecutarAudio

  public byte[] enviarAudio ()
  {
    return _impl.enviarAudio();
  } // enviarAudio

  public String[] obtenerSuscritos ()
  {
    return _impl.obtenerSuscritos();
  } // obtenerSuscritos

  private sop_corba.Interfaz_AdministradorOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class Interfaz_AdministradorPOATie
