package sop_corba;


/**
* sop_corba/Interfaz_Administrador.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* jueves 1 de junio de 2017 10:20:41 AM COT
*/

public interface Interfaz_Administrador extends Interfaz_AdministradorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Interfaz_Administrador
