package sop_corba;


/**
* sop_corba/Interfaz_Usuario.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* domingo 4 de junio de 2017 01:36:39 PM COT
*/

public interface Interfaz_Usuario extends Interfaz_UsuarioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Interfaz_Usuario
