package sop_corba;

/**
* sop_corba/Interfaz_AdministradorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* jueves 1 de junio de 2017 10:20:41 AM COT
*/

public final class Interfaz_AdministradorHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.Interfaz_Administrador value = null;

  public Interfaz_AdministradorHolder ()
  {
  }

  public Interfaz_AdministradorHolder (sop_corba.Interfaz_Administrador initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.Interfaz_AdministradorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.Interfaz_AdministradorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.Interfaz_AdministradorHelper.type ();
  }

}
