package sop_corba;


/**
* sop_corba/Interfaz_AdministradorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* domingo 4 de junio de 2017 01:36:39 PM COT
*/

public interface Interfaz_AdministradorOperations 
{
  boolean ingresoSistemaAdministrador (String login, String clave);
  boolean registrarUsuario (sop_corba.Usuario N_Usuario);
  sop_corba.Usuario[] consultarUsuarios ();
  sop_corba.Usuario consultarUsuario (String login);
  boolean exiteUsuario (String login);
  boolean actualizarUsuario (sop_corba.Usuario objUsuario, String login);
  boolean eliminarUsuario (String login);
  boolean seleccionarAudio (String ruta);
  boolean EjecutarAudio ();
  void enviarAudio (String loginUsuario, byte[] paquete);
  boolean suscribir_Usuario (sop_corba.usuarioCallbackInt objcllbck, String loginUsuario);
  boolean eliminarSuscripcion_Usuario (String loginUsuario);
  String[] obtenerSuscritos ();
  void notificarUsuario (String loginUsuario, String mensaje);
} // interface Interfaz_AdministradorOperations
