package sop_corba;

/**
* sop_corba/Interfaz_UsuarioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* jueves 1 de junio de 2017 11:29:38 AM COT
*/

public final class Interfaz_UsuarioHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.Interfaz_Usuario value = null;

  public Interfaz_UsuarioHolder ()
  {
  }

  public Interfaz_UsuarioHolder (sop_corba.Interfaz_Usuario initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.Interfaz_UsuarioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.Interfaz_UsuarioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.Interfaz_UsuarioHelper.type ();
  }

}
