package sop_corba;


/**
* sop_corba/Interfaz_AdministradorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* jueves 1 de junio de 2017 11:29:38 AM COT
*/

public abstract class Interfaz_AdministradorPOA extends org.omg.PortableServer.Servant
 implements sop_corba.Interfaz_AdministradorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ingresoSistemaAdministrador", new java.lang.Integer (0));
    _methods.put ("registrarUsuario", new java.lang.Integer (1));
    _methods.put ("consultarUsuarios", new java.lang.Integer (2));
    _methods.put ("consultarUsuario", new java.lang.Integer (3));
    _methods.put ("exiteUsuario", new java.lang.Integer (4));
    _methods.put ("actualizarUsuario", new java.lang.Integer (5));
    _methods.put ("eliminarUsuario", new java.lang.Integer (6));
    _methods.put ("seleccionarAudio", new java.lang.Integer (7));
    _methods.put ("EjecutarAudio", new java.lang.Integer (8));
    _methods.put ("enviarAudio", new java.lang.Integer (9));
    _methods.put ("obtenerSuscritos", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/Interfaz_Administrador/ingresoSistemaAdministrador
       {
         String login = in.read_string ();
         String clave = in.read_string ();
         boolean $result = false;
         $result = this.ingresoSistemaAdministrador (login, clave);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // sop_corba/Interfaz_Administrador/registrarUsuario
       {
         sop_corba.Usuario N_Usuario = sop_corba.UsuarioHelper.read (in);
         boolean $result = false;
         $result = this.registrarUsuario (N_Usuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // sop_corba/Interfaz_Administrador/consultarUsuarios
       {
         sop_corba.Usuario $result[] = null;
         $result = this.consultarUsuarios ();
         out = $rh.createReply();
         sop_corba.Interfaz_AdministradorPackage.ListUsuariosHelper.write (out, $result);
         break;
       }

       case 3:  // sop_corba/Interfaz_Administrador/consultarUsuario
       {
         String login = in.read_string ();
         sop_corba.Usuario $result = null;
         $result = this.consultarUsuario (login);
         out = $rh.createReply();
         sop_corba.UsuarioHelper.write (out, $result);
         break;
       }

       case 4:  // sop_corba/Interfaz_Administrador/exiteUsuario
       {
         String login = in.read_string ();
         boolean $result = false;
         $result = this.exiteUsuario (login);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // sop_corba/Interfaz_Administrador/actualizarUsuario
       {
         sop_corba.Usuario objUsuario = sop_corba.UsuarioHelper.read (in);
         String login = in.read_string ();
         boolean $result = false;
         $result = this.actualizarUsuario (objUsuario, login);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // sop_corba/Interfaz_Administrador/eliminarUsuario
       {
         String login = in.read_string ();
         boolean $result = false;
         $result = this.eliminarUsuario (login);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // sop_corba/Interfaz_Administrador/seleccionarAudio
       {
         String ruta = in.read_string ();
         boolean $result = false;
         $result = this.seleccionarAudio (ruta);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 8:  // sop_corba/Interfaz_Administrador/EjecutarAudio
       {
         boolean $result = false;
         $result = this.EjecutarAudio ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 9:  // sop_corba/Interfaz_Administrador/enviarAudio
       {
         byte $result[] = null;
         $result = this.enviarAudio ();
         out = $rh.createReply();
         sop_corba.Interfaz_AdministradorPackage.audioHelper.write (out, $result);
         break;
       }

       case 10:  // sop_corba/Interfaz_Administrador/obtenerSuscritos
       {
         String $result[] = null;
         $result = this.obtenerSuscritos ();
         out = $rh.createReply();
         sop_corba.Interfaz_AdministradorPackage.ListUsuariosSuscritosHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/Interfaz_Administrador:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Interfaz_Administrador _this() 
  {
    return Interfaz_AdministradorHelper.narrow(
    super._this_object());
  }

  public Interfaz_Administrador _this(org.omg.CORBA.ORB orb) 
  {
    return Interfaz_AdministradorHelper.narrow(
    super._this_object(orb));
  }


} // class Interfaz_AdministradorPOA
