package sop_corba;


/**
* sop_corba/usuarioCallbackIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* martes 6 de junio de 2017 10:16:52 AM COT
*/

public interface usuarioCallbackIntOperations 
{
  boolean resibirMensaje (String loginUsuario, String mensaje);
  void resibirAudio (String loginUsuario, byte[] paquete);
} // interface usuarioCallbackIntOperations
