package sop_corba;


/**
* sop_corba/usuarioSuscrito.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* martes 6 de junio de 2017 10:16:52 AM COT
*/

public final class usuarioSuscrito implements org.omg.CORBA.portable.IDLEntity
{
  public String loginUsuario = null;
  public sop_corba.usuarioCallbackInt objcllbck = null;

  public usuarioSuscrito ()
  {
  } // ctor

  public usuarioSuscrito (String _loginUsuario, sop_corba.usuarioCallbackInt _objcllbck)
  {
    loginUsuario = _loginUsuario;
    objcllbck = _objcllbck;
  } // ctor

    public String getLoginUsuario() {
        return loginUsuario;
    }

    public usuarioCallbackInt getObjcllbck() {
        return objcllbck;
    }

    public void setLoginUsuario(String loginUsuario) {
        this.loginUsuario = loginUsuario;
    }

    public void setObjcllbck(usuarioCallbackInt objcllbck) {
        this.objcllbck = objcllbck;
    }

} // class usuarioSuscrito
