package sop_corba;


/**
* sop_corba/usuarioCallbackIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* martes 6 de junio de 2017 10:16:52 AM COT
*/

public abstract class usuarioCallbackIntPOA extends org.omg.PortableServer.Servant
 implements sop_corba.usuarioCallbackIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("resibirMensaje", new java.lang.Integer (0));
    _methods.put ("resibirAudio", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/usuarioCallbackInt/resibirMensaje
       {
         String loginUsuario = in.read_string ();
         String mensaje = in.read_string ();
         boolean $result = false;
         $result = this.resibirMensaje (loginUsuario, mensaje);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // sop_corba/usuarioCallbackInt/resibirAudio
       {
         String loginUsuario = in.read_string ();
         byte paquete[] = sop_corba.usuarioCallbackIntPackage.audioHelper.read (in);
         this.resibirAudio (loginUsuario, paquete);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/usuarioCallbackInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public usuarioCallbackInt _this() 
  {
    return usuarioCallbackIntHelper.narrow(
    super._this_object());
  }

  public usuarioCallbackInt _this(org.omg.CORBA.ORB orb) 
  {
    return usuarioCallbackIntHelper.narrow(
    super._this_object(orb));
  }


} // class usuarioCallbackIntPOA
