package sop_corba;


/**
* sop_corba/usuarioSuscrito.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* s�bado 10 de junio de 2017 12:13:27 PM COT
*/

public final class usuarioSuscrito implements org.omg.CORBA.portable.IDLEntity
{
  public String loginUsuario = null;
  public sop_corba.usuarioCallbackInt objcllbck = null;
  public boolean notificado = false;
  public boolean aceptaEscuchar = false;

  public usuarioSuscrito ()
  {
  } // ctor

  public usuarioSuscrito (String _loginUsuario, sop_corba.usuarioCallbackInt _objcllbck, boolean _notificado, boolean _aceptaEscuchar)
  {
    loginUsuario = _loginUsuario;
    objcllbck = _objcllbck;
    notificado = _notificado;
    aceptaEscuchar = _aceptaEscuchar;
  } // ctor

    public String getLoginUsuario() {
        return loginUsuario;
    }

    public usuarioCallbackInt getObjcllbck() {
        return objcllbck;
    }

    public boolean isNotificado() {
        return notificado;
    }

    public boolean isAceptaEscuchar() {
        return aceptaEscuchar;
    }

    public void setLoginUsuario(String loginUsuario) {
        this.loginUsuario = loginUsuario;
    }

    public void setObjcllbck(usuarioCallbackInt objcllbck) {
        this.objcllbck = objcllbck;
    }

    public void setNotificado(boolean notificado) {
        this.notificado = notificado;
    }

    public void setAceptaEscuchar(boolean aceptaEscuchar) {
        this.aceptaEscuchar = aceptaEscuchar;
    }

} // class usuarioSuscrito
