package sop_corba;


/**
* sop_corba/usuarioCallbackIntPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* martes 6 de junio de 2017 10:16:52 AM COT
*/

public class usuarioCallbackIntPOATie extends usuarioCallbackIntPOA
{

  // Constructors

  public usuarioCallbackIntPOATie ( sop_corba.usuarioCallbackIntOperations delegate ) {
      this._impl = delegate;
  }
  public usuarioCallbackIntPOATie ( sop_corba.usuarioCallbackIntOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public sop_corba.usuarioCallbackIntOperations _delegate() {
      return this._impl;
  }
  public void _delegate (sop_corba.usuarioCallbackIntOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean resibirMensaje (String loginUsuario, String mensaje)
  {
    return _impl.resibirMensaje(loginUsuario, mensaje);
  } // resibirMensaje

  public void resibirAudio (String loginUsuario, byte[] paquete)
  {
    _impl.resibirAudio(loginUsuario, paquete);
  } // resibirAudio

  private sop_corba.usuarioCallbackIntOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class usuarioCallbackIntPOATie
