package sop_corba;

/**
* sop_corba/UsuarioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* jueves 1 de junio de 2017 11:29:37 AM COT
*/

public final class UsuarioHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.Usuario value = null;

  public UsuarioHolder ()
  {
  }

  public UsuarioHolder (sop_corba.Usuario initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.UsuarioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.UsuarioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.UsuarioHelper.type ();
  }

}
