package sop_corba;


/**
* sop_corba/usuarioCallbackIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* sábado 10 de junio de 2017 12:13:27 PM COT
*/

public interface usuarioCallbackIntOperations 
{
  void actualizarSuscritos (String[] ListUsuariosSuscritos);
  boolean resibirMensaje (String mensaje);
  void resibirAudio (byte[] paquete);
} // interface usuarioCallbackIntOperations
