package sop_corba.autenticacionUsuarioPackage;


/**
* sop_corba/autenticacionUsuarioPackage/usuariosActivosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* martes 6 de junio de 2017 10:16:52 AM COT
*/

public final class usuariosActivosHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public usuariosActivosHolder ()
  {
  }

  public usuariosActivosHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.autenticacionUsuarioPackage.usuariosActivosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.autenticacionUsuarioPackage.usuariosActivosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.autenticacionUsuarioPackage.usuariosActivosHelper.type ();
  }

}
