package cliente;

import java.awt.Color;
import javax.swing.JOptionPane;
import org.omg.CORBA.ORB;
import org.omg.CosNaming.NamingContextExt;
import org.omg.CosNaming.NamingContextExtHelper;
import org.omg.PortableServer.POA;
import org.omg.PortableServer.POAHelper;
import sop_corba.*;

/**
 * @author Santiago Garcia Ch
 */
public class conexion extends javax.swing.JFrame {

    public static String DireccionIP;
    public static int NumeroPuerto;
    /**
     * Creates new form InicioSesion
     */
    public conexion() {
        initComponents();
        panelTransparente.setBackground(new Color(0,0,0,200));
        setLocationRelativeTo(this);
        DireccionIP = "";
        NumeroPuerto = 0;
        this.campoMensaje.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTransparente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoPuerto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botonConectar = new java.awt.Button();
        botonCerrar = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        campoMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTransparente.setBackground(new java.awt.Color(32, 33, 35));
        panelTransparente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 102, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(57, 113, 177));
        jLabel4.setText("Streaming musica");
        panelTransparente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Creado por");
        panelTransparente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Santiago Garcia y Kevin Chantre");
        panelTransparente.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Servicio de musica implementado en CORBA");
        panelTransparente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 113, 177));
        jLabel2.setText("Direccion host");
        panelTransparente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        campoPuerto.setBackground(new java.awt.Color(32, 33, 35));
        campoPuerto.setForeground(new java.awt.Color(255, 255, 255));
        campoPuerto.setBorder(null);
        panelTransparente.add(campoPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 230, -1));
        panelTransparente.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 230, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(57, 113, 177));
        jLabel3.setText("Puerto");
        panelTransparente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
        panelTransparente.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 230, 10));

        botonConectar.setBackground(new java.awt.Color(126, 87, 194));
        botonConectar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        botonConectar.setForeground(new java.awt.Color(255, 255, 255));
        botonConectar.setLabel("Conectarme");
        botonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConectarActionPerformed(evt);
            }
        });
        panelTransparente.add(botonConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 142, -1));

        botonCerrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        botonCerrar.setForeground(new java.awt.Color(57, 113, 177));
        botonCerrar.setText(" X ");
        botonCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarMouseClicked(evt);
            }
        });
        panelTransparente.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        campoDireccion.setBackground(new java.awt.Color(32, 33, 35));
        campoDireccion.setForeground(new java.awt.Color(255, 255, 255));
        campoDireccion.setBorder(null);
        panelTransparente.add(campoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 230, -1));

        campoMensaje.setBackground(new java.awt.Color(32, 33, 35));
        campoMensaje.setForeground(new java.awt.Color(255, 0, 0));
        panelTransparente.add(campoMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 310, 20));

        getContentPane().add(panelTransparente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_botonCerrarMouseClicked

    private void botonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConectarActionPerformed
        boolean error = false;
        String direccion = campoDireccion.getText();
        String puerto = campoPuerto.getText();
        if(direccion.equals("") || puerto.equals("")){
            System.out.println("Campo Invalido....Verifique la informacion..");
            this.campoMensaje.setText("Los campos no pueden estar vacios");
        }else{
            DireccionIP = direccion;
            try{
                NumeroPuerto = Integer.parseInt(puerto);
            }catch(Exception e){
                error = true;
                System.out.println("Problemas en la conversion del puerto: "+e);
                this.campoMensaje.setText("El puerto debe ser un numero");
            }
            if(!error){
                ClienteDeObjetos objc = new ClienteDeObjetos();
                String[] datos = new String[4];
                datos[0] = "-ORBInitialHost";
                datos[1] = DireccionIP;
                datos[2] = "-ORBInitialPort";
                datos[3] = Integer.toString(NumeroPuerto);

                if(objc.iniciarORB(datos)){
                    InicioSesion objInicio = new InicioSesion(objc);
                    objInicio.setVisible(true);
                    this.setVisible(false);
                }else{
                    this.campoMensaje.setVisible(true);
                    this.campoMensaje.setText("Error conexion. Verifique los datos");
                    System.out.println("Error. No fue posible iniciar el ORB.....");
                }
            }
        } 
    }//GEN-LAST:event_botonConectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        //</editor-fold>
        //</editor-fold>
            
        /* Create and display the form */
        System.out.println("Iniciando conexion");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonCerrar;
    private java.awt.Button botonConectar;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JLabel campoMensaje;
    private javax.swing.JTextField campoPuerto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelTransparente;
    // End of variables declaration//GEN-END:variables
}
