package cliente;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import servidor.usuarioCallbackImpl;
import sop_corba.Interfaz_Administrador;
import sop_corba.Interfaz_Gestion;
import sop_corba.Usuario;
import sop_corba.autenticacionUsuario;
import sop_corba.usuarioCallbackInt;

/**
 *
 * @author Santiago Garcia Ch
 */
public class DashboardCliente extends javax.swing.JFrame {

    private autenticacionUsuario autenticacion;
    private Interfaz_Gestion gestion;
    private Interfaz_Administrador admin;
    private String loginActual;
    private usuarioCallbackImpl usuario;
    private boolean suscripcion;
    
    /**
     * Creates new form Dashboard
     */
    public DashboardCliente(String login) {
        initComponents();
        this.setLocationRelativeTo(this);
        loginActual = login;
        this.usuarioIniciado.setText(login);
        obtenerObjetosRemotos();
        this.suscripcion = false;
        this.estadoSuscripcion.setText("No suscrito");
        /*Debemos establecer el objeto Callback*/
        usuario = new usuarioCallbackImpl(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraPrograma = new javax.swing.JPanel();
        botonCerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ContenedorDatosSesion = new javax.swing.JPanel();
        usuarioIniciado = new javax.swing.JLabel();
        botonCerrarSesion = new javax.swing.JLabel();
        contenedorGeneral = new javax.swing.JPanel();
        contenedorBienvenida = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoBienvenida = new javax.swing.JTextArea();
        botonEditarPerfil = new javax.swing.JButton();
        contenedorOpciones = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonSuscribirme = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        botonEliminarSuscripcion = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        estadoSuscripcion = new javax.swing.JLabel();
        contenedorReproductor = new javax.swing.JPanel();
        nombreCancion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraPrograma.setBackground(new java.awt.Color(32, 33, 35));
        BarraPrograma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BarraPrograma.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCerrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        botonCerrar.setForeground(new java.awt.Color(57, 113, 177));
        botonCerrar.setText(" X ");
        botonCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarMouseClicked(evt);
            }
        });
        BarraPrograma.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 13, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 113, 177));
        jLabel1.setText("Streaming Musica");
        BarraPrograma.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 15, -1, -1));

        getContentPane().add(BarraPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        ContenedorDatosSesion.setBackground(new java.awt.Color(0, 18, 50));
        ContenedorDatosSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ContenedorDatosSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioIniciado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        usuarioIniciado.setForeground(new java.awt.Color(255, 255, 255));
        usuarioIniciado.setIcon(new javax.swing.ImageIcon("D:\\Santiago\\Imagenes\\iconos PNG\\usuario.png")); // NOI18N
        usuarioIniciado.setText("Usuario");
        usuarioIniciado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioIniciadoMouseClicked(evt);
            }
        });
        ContenedorDatosSesion.add(usuarioIniciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        botonCerrarSesion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonCerrarSesion.setForeground(new java.awt.Color(126, 87, 194));
        botonCerrarSesion.setText("Cerrar sesion");
        botonCerrarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarSesionMouseClicked(evt);
            }
        });
        ContenedorDatosSesion.add(botonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        getContentPane().add(ContenedorDatosSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 760, 50));

        contenedorGeneral.setBackground(new java.awt.Color(32, 47, 90));
        contenedorGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setText("Bienvenido");

        textoBienvenida.setBackground(new java.awt.Color(240, 240, 240));
        textoBienvenida.setColumns(20);
        textoBienvenida.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textoBienvenida.setRows(5);
        textoBienvenida.setText("Conectate con la musica!\nSintoniza lo que se esta\nreproduciendo el servidor.\n\nDesde aqui podras escuchar musica \ny editar tu perfil\n\n");
        textoBienvenida.setAutoscrolls(false);
        textoBienvenida.setBorder(null);
        jScrollPane3.setViewportView(textoBienvenida);

        botonEditarPerfil.setText("Editar mi perfil");
        botonEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedorBienvenidaLayout = new javax.swing.GroupLayout(contenedorBienvenida);
        contenedorBienvenida.setLayout(contenedorBienvenidaLayout);
        contenedorBienvenidaLayout.setHorizontalGroup(
            contenedorBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorBienvenidaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(112, 112, 112))
            .addGroup(contenedorBienvenidaLayout.createSequentialGroup()
                .addGroup(contenedorBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorBienvenidaLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenedorBienvenidaLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(botonEditarPerfil)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        contenedorBienvenidaLayout.setVerticalGroup(
            contenedorBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorBienvenidaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEditarPerfil)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        contenedorGeneral.add(contenedorBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 48, 320, 310));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("Suscribete");

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel6.setText("Empieza a escuchar lo que se esta reproducciendo");

        botonSuscribirme.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonSuscribirme.setText("Suscribirme");
        botonSuscribirme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSuscribirmeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel11.setText("Eliminar suscripcion");

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel13.setText("Ya no quieres escuchar? elimina la suscripcion");

        botonEliminarSuscripcion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonEliminarSuscripcion.setText("Eliminar suscripcion");
        botonEliminarSuscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarSuscripcionActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel14.setText("Suscripcion");

        javax.swing.GroupLayout contenedorOpcionesLayout = new javax.swing.GroupLayout(contenedorOpciones);
        contenedorOpciones.setLayout(contenedorOpcionesLayout);
        contenedorOpcionesLayout.setHorizontalGroup(
            contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                .addGroup(contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorOpcionesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                        .addGroup(contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel11))
                            .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(botonEliminarSuscripcion))
                            .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(8, 8, 8)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(contenedorOpcionesLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(botonSuscribirme)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorOpcionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(estadoSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        contenedorOpcionesLayout.setVerticalGroup(
            contenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadoSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSuscribirme)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEliminarSuscripcion)
                .addGap(38, 38, 38))
        );

        contenedorGeneral.add(contenedorOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 310));

        getContentPane().add(contenedorGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 760, 380));

        contenedorReproductor.setBackground(new java.awt.Color(32, 33, 35));
        contenedorReproductor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contenedorReproductor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreCancion.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        nombreCancion.setForeground(new java.awt.Color(255, 255, 255));
        nombreCancion.setText("Nombre cancion");
        contenedorReproductor.add(nombreCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 22, 244, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(126, 87, 194));
        jLabel12.setText("Cancion actual:");
        contenedorReproductor.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        getContentPane().add(contenedorReproductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 760, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseClicked
        if(JOptionPane.showConfirmDialog(null, "Esta seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION) == 0){
            if(autenticacion.salir(loginActual)){
                System.out.println("Has salido. Sesion cerrada");
                this.setVisible(false);
                InicioSesion inicio = new InicioSesion();
                inicio.setVisible(true);
            }else{
                System.out.println("Error al cerrar sesion");
            }
        }else{
            System.out.println("Cancelado cierre de sesion");
        }
    }//GEN-LAST:event_botonCerrarMouseClicked

    private void usuarioIniciadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioIniciadoMouseClicked

    }//GEN-LAST:event_usuarioIniciadoMouseClicked

    private void botonCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarSesionMouseClicked
        if(JOptionPane.showConfirmDialog(null, "Esta seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION) == 0){
            if(autenticacion.salir(loginActual)){
                System.out.println("Has salido. Sesion cerrada");
                this.setVisible(false);
                InicioSesion inicio = new InicioSesion();
                inicio.setVisible(true);
            }else{
                System.out.println("Error al cerrar sesion");
            }
        }else{
            System.out.println("Cancelado cierre de sesion");
        }
    }//GEN-LAST:event_botonCerrarSesionMouseClicked

    private void botonSuscribirmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSuscribirmeActionPerformed
        if(suscripcion){
            JOptionPane.showMessageDialog(null,"Ya estas suscrito");
        }else{
            if(admin.suscribir_Usuario((usuarioCallbackInt) usuario, loginActual)){
                System.out.println("Te has suscrito");
                this.estadoSuscripcion.setText("Suscrito");
                suscripcion = true;
            }
        }
        
    }//GEN-LAST:event_botonSuscribirmeActionPerformed

    private void botonEliminarSuscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarSuscripcionActionPerformed
        if(!suscripcion){
            JOptionPane.showMessageDialog(null,"No te has suscrito");
        }else{
            if(admin.eliminarSuscripcion_Usuario(loginActual)){
                System.out.println("Suscripcion eliminada");
                this.estadoSuscripcion.setText("No suscrito");
                suscripcion = false;
            }
        }
    }//GEN-LAST:event_botonEliminarSuscripcionActionPerformed

    private void botonEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarPerfilActionPerformed
        // TODO add your handling code here:
        EditarDatosCliente editar = new EditarDatosCliente(loginActual,this);
        editar.setVisible(true);
    }//GEN-LAST:event_botonEditarPerfilActionPerformed

    public void obtenerObjetosRemotos(){
        String direccion = conexion.DireccionIP;
        int puerto = conexion.NumeroPuerto;

        ClienteDeObjetos objc = new ClienteDeObjetos();
        String[] datos = new String[4];
        datos[0] = "-ORBInitialHost";
        datos[1] = conexion.DireccionIP;
        datos[2] = "-ORBInitialPort";
        datos[3] = Integer.toString(conexion.NumeroPuerto);

        if(objc.iniciarORB(datos)){
            /*Comprobamos los datos*/
            autenticacion = (autenticacionUsuario) objc.ObtenerServant("ServantAuten");
            gestion = (Interfaz_Gestion) objc.ObtenerServant("ServantGest");
            admin = (Interfaz_Administrador) objc.ObtenerServant("ServantAdmin");
        }else{
            System.out.println("Error. No fue posible iniciar el ORB.....");
        }
    }
    
    public void actualizarInformacion(String login){
        Usuario u = gestion.consultarUsuario(login);
        this.loginActual = u.getLoginUsuario();
        this.usuarioIniciado.setText(loginActual);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardCliente("Usuario").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraPrograma;
    private javax.swing.JPanel ContenedorDatosSesion;
    private javax.swing.JLabel botonCerrar;
    private javax.swing.JLabel botonCerrarSesion;
    private javax.swing.JButton botonEditarPerfil;
    private javax.swing.JButton botonEliminarSuscripcion;
    private javax.swing.JButton botonSuscribirme;
    private javax.swing.JPanel contenedorBienvenida;
    private javax.swing.JPanel contenedorGeneral;
    private javax.swing.JPanel contenedorOpciones;
    private javax.swing.JPanel contenedorReproductor;
    private javax.swing.JLabel estadoSuscripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nombreCancion;
    private javax.swing.JTextArea textoBienvenida;
    private javax.swing.JLabel usuarioIniciado;
    // End of variables declaration//GEN-END:variables
}
