package cliente;

import java.awt.Panel;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import servidor.usuarioCallbackImpl;
import sop_corba.Interfaz_Administrador;
import sop_corba.Interfaz_Gestion;
import sop_corba.Usuario;
import sop_corba.autenticacionUsuario;
import sop_corba.usuarioCallbackInt;

/**
 * @author Santiago Garcia Ch
 */

public class Dashboard extends javax.swing.JFrame {

    private autenticacionUsuario autenticacion;
    private Interfaz_Gestion gestion;
    private Interfaz_Administrador admin;
    private String loginActual;
    private String rutaCancion;
    private String loginSeleccionado;
    private usuarioCallbackImpl usuario;
    private boolean suscripcion;
    private ClienteDeObjetos objc;
    public boolean isAdmin;
    /**
     * Creates new form Dashboard
     */
    public Dashboard(ClienteDeObjetos objc, String login, boolean esAdmin) {
        initComponents();
        contenedorInfoUsuario.setVisible(false);
        this.setLocationRelativeTo(this);
        this.objc = objc;
        obtenerObjetosRemotos();
        loginActual = login;
        usuarioIniciado.setText(login);
        this.isAdmin = esAdmin;
        if(esAdmin){
            actualizarListaRegistrados();
            actualizarListaSuscritos();
            dashboardAdmin();
        }else{
            dashboardCliente();
        }
    }
    
    /*Funciones para establecer el dashboard segun el tipo de usuario*/
    public void dashboardCliente(){
        /*Ocultamos los paneles del administrador*/
        this.contenedorReproductor.setVisible(false);
        this.contenedorBienvenida.setVisible(false);
        this.contenedorPaneles.setVisible(false);
        /*Mostramos las del cliente*/
        this.contenedorReproductorCliente.setVisible(true);
        this.contenedorBienvenidaCliente.setVisible(true);
        this.contenedorSuscripcion.setVisible(true);
    }
    
    public void dashboardAdmin(){
        /*Mostrar los paneles del administrador*/
        this.contenedorReproductor.setVisible(true);
        this.contenedorBienvenida.setVisible(true);
        this.contenedorPaneles.setVisible(true);
        /*Ocultar las del cliente*/
        this.contenedorReproductorCliente.setVisible(false);
        this.contenedorBienvenidaCliente.setVisible(false);
        this.contenedorSuscripcion.setVisible(false);
    }

    private Dashboard(String usuario) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraPrograma = new javax.swing.JPanel();
        botonCerrar = new javax.swing.JLabel();
        tituloApp = new javax.swing.JLabel();
        ContenedorDatosSesion = new javax.swing.JPanel();
        usuarioIniciado = new javax.swing.JLabel();
        botonCerrarSesion = new javax.swing.JLabel();
        contenedorGeneral = new javax.swing.JPanel();
        contenedorPaneles = new javax.swing.JTabbedPane();
        contenedorUsuariosConectados = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaConectados = new javax.swing.JList<>();
        contenedorUsuariosRegistrados = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaRegistrados = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        contenedorBienvenida = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoBienvenida = new javax.swing.JTextArea();
        contenedorInfoUsuario = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botonEditar = new javax.swing.JButton();
        botonDesactivar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        campoNombre = new javax.swing.JLabel();
        campoApellidos = new javax.swing.JLabel();
        campoLogin = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoEstado = new javax.swing.JLabel();
        contenedorSuscripcion = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        botonSuscribirme = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        botonEliminarSuscripcion = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        estadoSuscripcion = new javax.swing.JLabel();
        contenedorBienvenidaCliente = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textoBienvenida1 = new javax.swing.JTextArea();
        botonEditarPerfilUsuario = new javax.swing.JButton();
        contenedorReproductor = new javax.swing.JPanel();
        botonSelecionarCancion = new java.awt.Button();
        nombreCancion = new javax.swing.JLabel();
        botonReproducir = new javax.swing.JLabel();
        botonPausa = new javax.swing.JLabel();
        contenedorReproductorCliente = new javax.swing.JPanel();
        nombreCancion1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraPrograma.setBackground(new java.awt.Color(32, 33, 35));
        BarraPrograma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BarraPrograma.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCerrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        botonCerrar.setForeground(new java.awt.Color(57, 113, 177));
        botonCerrar.setText(" X ");
        botonCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarMouseClicked(evt);
            }
        });
        BarraPrograma.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 13, -1, -1));

        tituloApp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tituloApp.setForeground(new java.awt.Color(57, 113, 177));
        tituloApp.setText("Streaming Musica");
        BarraPrograma.add(tituloApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 15, -1, -1));

        getContentPane().add(BarraPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        ContenedorDatosSesion.setBackground(new java.awt.Color(0, 18, 50));
        ContenedorDatosSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ContenedorDatosSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioIniciado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        usuarioIniciado.setForeground(new java.awt.Color(255, 255, 255));
        usuarioIniciado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        usuarioIniciado.setText("Usuario");
        usuarioIniciado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioIniciadoMouseClicked(evt);
            }
        });
        ContenedorDatosSesion.add(usuarioIniciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        botonCerrarSesion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonCerrarSesion.setForeground(new java.awt.Color(126, 87, 194));
        botonCerrarSesion.setText("Cerrar sesion");
        botonCerrarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarSesionMouseClicked(evt);
            }
        });
        ContenedorDatosSesion.add(botonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        getContentPane().add(ContenedorDatosSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 760, 50));

        contenedorGeneral.setBackground(new java.awt.Color(32, 47, 90));
        contenedorGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel11.setText("Usuarios conectados");

        listaConectados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listaConectados);

        javax.swing.GroupLayout contenedorUsuariosConectadosLayout = new javax.swing.GroupLayout(contenedorUsuariosConectados);
        contenedorUsuariosConectados.setLayout(contenedorUsuariosConectadosLayout);
        contenedorUsuariosConectadosLayout.setHorizontalGroup(
            contenedorUsuariosConectadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorUsuariosConectadosLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(67, 67, 67))
            .addGroup(contenedorUsuariosConectadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contenedorUsuariosConectadosLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(61, Short.MAX_VALUE)))
        );
        contenedorUsuariosConectadosLayout.setVerticalGroup(
            contenedorUsuariosConectadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorUsuariosConectadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(266, Short.MAX_VALUE))
            .addGroup(contenedorUsuariosConectadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contenedorUsuariosConectadosLayout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        contenedorPaneles.addTab("Usuarios conectados", contenedorUsuariosConectados);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("Usuarios registrados");

        listaRegistrados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaRegistrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaRegistradosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaRegistrados);

        jButton1.setText("Crear usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel6.setText("Selecciona un usuario para ver su informacion");

        javax.swing.GroupLayout contenedorUsuariosRegistradosLayout = new javax.swing.GroupLayout(contenedorUsuariosRegistrados);
        contenedorUsuariosRegistrados.setLayout(contenedorUsuariosRegistradosLayout);
        contenedorUsuariosRegistradosLayout.setHorizontalGroup(
            contenedorUsuariosRegistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorUsuariosRegistradosLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorUsuariosRegistradosLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(contenedorUsuariosRegistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorUsuariosRegistradosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorUsuariosRegistradosLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorUsuariosRegistradosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())))
        );
        contenedorUsuariosRegistradosLayout.setVerticalGroup(
            contenedorUsuariosRegistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorUsuariosRegistradosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        contenedorPaneles.addTab("Usuarios registrados", contenedorUsuariosRegistrados);

        contenedorGeneral.add(contenedorPaneles, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 28, -1, 330));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setText("Bienvenido");

        textoBienvenida.setBackground(new java.awt.Color(240, 240, 240));
        textoBienvenida.setColumns(20);
        textoBienvenida.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textoBienvenida.setRows(5);
        textoBienvenida.setText("Selecciona un cancion y empieza\na compartir con tus usuarios\nsuscritos.\n\nDesde aqui podras crear un \nnuevo usuario, editar su \ninformacion y desactivar usuarios.");
        textoBienvenida.setAutoscrolls(false);
        textoBienvenida.setBorder(null);
        jScrollPane3.setViewportView(textoBienvenida);

        javax.swing.GroupLayout contenedorBienvenidaLayout = new javax.swing.GroupLayout(contenedorBienvenida);
        contenedorBienvenida.setLayout(contenedorBienvenidaLayout);
        contenedorBienvenidaLayout.setHorizontalGroup(
            contenedorBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorBienvenidaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorBienvenidaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(112, 112, 112))
        );
        contenedorBienvenidaLayout.setVerticalGroup(
            contenedorBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorBienvenidaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        contenedorGeneral.add(contenedorBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 48, 320, 310));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Informacion usuario");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Nombres:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setText("Apellidos:");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setText("Login:");

        botonEditar.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonDesactivar.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        botonDesactivar.setText("Desactivar");
        botonDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDesactivarActionPerformed(evt);
            }
        });

        botonAceptar.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel12.setText("Estado:");

        javax.swing.GroupLayout contenedorInfoUsuarioLayout = new javax.swing.GroupLayout(contenedorInfoUsuario);
        contenedorInfoUsuario.setLayout(contenedorInfoUsuarioLayout);
        contenedorInfoUsuarioLayout.setHorizontalGroup(
            contenedorInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorInfoUsuarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(contenedorInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorInfoUsuarioLayout.createSequentialGroup()
                        .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonDesactivar)
                        .addGap(18, 18, 18)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenedorInfoUsuarioLayout.createSequentialGroup()
                        .addGroup(contenedorInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(contenedorInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(contenedorInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(contenedorInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                            .addComponent(campoEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        contenedorInfoUsuarioLayout.setVerticalGroup(
            contenedorInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorInfoUsuarioLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(contenedorInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(contenedorInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(contenedorInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedorInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(contenedorInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEditar)
                    .addComponent(botonDesactivar)
                    .addComponent(botonAceptar))
                .addGap(26, 26, 26))
        );

        contenedorGeneral.add(contenedorInfoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 48, 320, 310));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel14.setText("Suscribete");

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel15.setText("Empieza a escuchar lo que se esta reproducciendo");

        botonSuscribirme.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonSuscribirme.setText("Suscribirme");
        botonSuscribirme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSuscribirmeActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel16.setText("Eliminar suscripcion");

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel17.setText("Ya no quieres escuchar? elimina la suscripcion");

        botonEliminarSuscripcion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        botonEliminarSuscripcion.setText("Eliminar suscripcion");
        botonEliminarSuscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarSuscripcionActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel18.setText("Suscripcion");

        javax.swing.GroupLayout contenedorSuscripcionLayout = new javax.swing.GroupLayout(contenedorSuscripcion);
        contenedorSuscripcion.setLayout(contenedorSuscripcionLayout);
        contenedorSuscripcionLayout.setHorizontalGroup(
            contenedorSuscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorSuscripcionLayout.createSequentialGroup()
                .addGroup(contenedorSuscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorSuscripcionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(contenedorSuscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(contenedorSuscripcionLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(contenedorSuscripcionLayout.createSequentialGroup()
                        .addGroup(contenedorSuscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorSuscripcionLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel16))
                            .addGroup(contenedorSuscripcionLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(botonEliminarSuscripcion))
                            .addGroup(contenedorSuscripcionLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(contenedorSuscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addGroup(contenedorSuscripcionLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(8, 8, 8)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(contenedorSuscripcionLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(botonSuscribirme)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorSuscripcionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(estadoSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        contenedorSuscripcionLayout.setVerticalGroup(
            contenedorSuscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorSuscripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadoSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSuscribirme)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEliminarSuscripcion)
                .addGap(38, 38, 38))
        );

        contenedorGeneral.add(contenedorSuscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 310));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel19.setText("Bienvenido");

        textoBienvenida1.setBackground(new java.awt.Color(240, 240, 240));
        textoBienvenida1.setColumns(20);
        textoBienvenida1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textoBienvenida1.setRows(5);
        textoBienvenida1.setText("Conectate con la musica!\nSintoniza lo que se esta\nreproduciendo el servidor.\n\nDesde aqui podras escuchar musica \ny editar tu perfil\n\n");
        textoBienvenida1.setAutoscrolls(false);
        textoBienvenida1.setBorder(null);
        jScrollPane5.setViewportView(textoBienvenida1);

        botonEditarPerfilUsuario.setText("Editar mi perfil");
        botonEditarPerfilUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarPerfilUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedorBienvenidaClienteLayout = new javax.swing.GroupLayout(contenedorBienvenidaCliente);
        contenedorBienvenidaCliente.setLayout(contenedorBienvenidaClienteLayout);
        contenedorBienvenidaClienteLayout.setHorizontalGroup(
            contenedorBienvenidaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorBienvenidaClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(112, 112, 112))
            .addGroup(contenedorBienvenidaClienteLayout.createSequentialGroup()
                .addGroup(contenedorBienvenidaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorBienvenidaClienteLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenedorBienvenidaClienteLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(botonEditarPerfilUsuario)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        contenedorBienvenidaClienteLayout.setVerticalGroup(
            contenedorBienvenidaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorBienvenidaClienteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEditarPerfilUsuario)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        contenedorGeneral.add(contenedorBienvenidaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 48, 320, 310));

        getContentPane().add(contenedorGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 760, 380));

        contenedorReproductor.setBackground(new java.awt.Color(32, 33, 35));
        contenedorReproductor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contenedorReproductor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSelecionarCancion.setBackground(new java.awt.Color(126, 87, 194));
        botonSelecionarCancion.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        botonSelecionarCancion.setForeground(new java.awt.Color(255, 255, 255));
        botonSelecionarCancion.setLabel("Seleccionar cancion");
        botonSelecionarCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSelecionarCancionMouseClicked(evt);
            }
        });
        contenedorReproductor.add(botonSelecionarCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 20, -1, 32));

        nombreCancion.setForeground(new java.awt.Color(255, 255, 255));
        nombreCancion.setText("Nombre cancion");
        contenedorReproductor.add(nombreCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 20, 244, 32));

        botonReproducir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-reproduccion.png"))); // NOI18N
        botonReproducir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonReproducirMouseClicked(evt);
            }
        });
        contenedorReproductor.add(botonReproducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        botonPausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pausa.png"))); // NOI18N
        contenedorReproductor.add(botonPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        getContentPane().add(contenedorReproductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 760, 70));

        contenedorReproductorCliente.setBackground(new java.awt.Color(32, 33, 35));
        contenedorReproductorCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contenedorReproductorCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreCancion1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        nombreCancion1.setForeground(new java.awt.Color(255, 255, 255));
        nombreCancion1.setText("Nombre cancion");
        contenedorReproductorCliente.add(nombreCancion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 22, 244, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(126, 87, 194));
        jLabel13.setText("Cancion actual:");
        contenedorReproductorCliente.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        getContentPane().add(contenedorReproductorCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 760, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseClicked
        if(JOptionPane.showConfirmDialog(null, "Esta seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION) == 0){
            if(autenticacion.salir(loginActual)){
                System.out.println("Has salido. Sesion cerrada");
                this.setVisible(false);
                InicioSesion inicio = new InicioSesion(objc);
                inicio.setVisible(true);
            }else{
                System.out.println("Error al cerrar sesion");
            }
        }else{
            System.out.println("Cancelado cierre de sesion");
        }
    }//GEN-LAST:event_botonCerrarMouseClicked

    private void botonSelecionarCancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSelecionarCancionMouseClicked
        // TODO add your handling code here:
        JFileChooser explorador = new JFileChooser();
        explorador.setDialogTitle("Buscar cancion");
        /*Agregamos el filtro*/
        explorador.setFileFilter(new FileNameExtensionFilter("Mp3","mp3"));
        explorador.showOpenDialog(null);
        File archivo = explorador.getSelectedFile();
        rutaCancion = archivo.getPath();
        /*actualizamos el nombre*/
        this.nombreCancion.setText(archivo.getName());
        System.out.println("Ruta seleccionada "+rutaCancion);
    }//GEN-LAST:event_botonSelecionarCancionMouseClicked

    private void listaRegistradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaRegistradosMouseClicked
        // TODO add your handling code here:
        if(listaRegistrados.isSelectionEmpty()){
            System.out.println("");
        }else{
            /*Obtenemos el login seleccionado y buscamos los datos para 
             mostrarlos en el panel de la derecha*/
            loginSeleccionado = listaRegistrados.getSelectedValue();
            System.out.println("Login seleccionado: "+loginSeleccionado);
            Usuario usuario = gestion.consultarUsuario(loginSeleccionado);
            contenedorBienvenida.setVisible(false);
            contenedorInfoUsuario.setVisible(true);
            actualizarPanelInfoUsuario(usuario);
        }
    }//GEN-LAST:event_listaRegistradosMouseClicked

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        limpiarPanelInfoUsuario();
        contenedorInfoUsuario.setVisible(false);
        contenedorBienvenida.setVisible(true);
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        // TODO add your handling code here:
        InterfazDatosUsuario editar = new InterfazDatosUsuario(objc ,this,false,loginSeleccionado);
        editar.setVisible(true);
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDesactivarActionPerformed
        /*Consultamos el estado del usuario para saber si esta activo o no*/
        Usuario usuario = gestion.consultarUsuario(loginSeleccionado);
        String mensagePregunta, mensageConfirmacion, mensageError;
        if(usuario.desactivado){
            mensagePregunta= "Esta seguro que desea activar este usuario?";
            mensageConfirmacion = "El usuario ha sido activado";
            mensageError = "El usuario no ha sido activado";
        }else{
            mensagePregunta = "Esta seguro que desea desactivar este usuario?";
            mensageConfirmacion = "El usuario ha sido desactivado";
            mensageError = "El usuario no ha sido desactivado";
        }
        if(JOptionPane.showConfirmDialog(null, mensagePregunta, "Confirmar accion", JOptionPane.YES_NO_OPTION) == 0){
            if(gestion.eliminarUsuario(loginSeleccionado)){
                JOptionPane.showMessageDialog(null,mensageConfirmacion );
                System.out.println(mensageConfirmacion);
                Usuario u = gestion.consultarUsuario(loginSeleccionado);
                actualizarPanelInfoUsuario(u);
            }else{
                System.out.println(mensageError);
                JOptionPane.showMessageDialog(null,mensageError );
            }
        }else{
            System.out.println("Ha cancelado la accion");
        }

    }//GEN-LAST:event_botonDesactivarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        InterfazDatosUsuario crear = new InterfazDatosUsuario(objc ,this,true,"");
        crear.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usuarioIniciadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioIniciadoMouseClicked

    }//GEN-LAST:event_usuarioIniciadoMouseClicked

    private void botonCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarSesionMouseClicked
        if(JOptionPane.showConfirmDialog(null, "Esta seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION) == 0){
            System.out.println("Has salido. Sesion cerrada");
            this.setVisible(false);
            InicioSesion inicio = new InicioSesion(objc);
            inicio.setVisible(true);
        }else{
            System.out.println("Cancelado cierre de sesion");
        }
    }//GEN-LAST:event_botonCerrarSesionMouseClicked

    private void botonReproducirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReproducirMouseClicked
        /*Reproducir cancion*/
        admin.seleccionarAudio(rutaCancion);
        admin.EjecutarAudio();
    }//GEN-LAST:event_botonReproducirMouseClicked

    private void botonSuscribirmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSuscribirmeActionPerformed
        if(suscripcion){
            JOptionPane.showMessageDialog(null,"Ya estas suscrito");
        }else{
            if(admin.suscribir_Usuario((usuarioCallbackInt) usuario, loginActual)){
                System.out.println("Te has suscrito");
                this.estadoSuscripcion.setText("Suscrito");
                suscripcion = true;
            }
        }

    }//GEN-LAST:event_botonSuscribirmeActionPerformed

    private void botonEliminarSuscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarSuscripcionActionPerformed
        if(!suscripcion){
            JOptionPane.showMessageDialog(null,"No te has suscrito");
        }else{
            if(admin.eliminarSuscripcion_Usuario(loginActual)){
                System.out.println("Suscripcion eliminada");
                this.estadoSuscripcion.setText("No suscrito");
                suscripcion = false;
            }
        }
    }//GEN-LAST:event_botonEliminarSuscripcionActionPerformed

    private void botonEditarPerfilUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarPerfilUsuarioActionPerformed
        // TODO add your handling code here:
        InterfazDatosUsuario editar = new InterfazDatosUsuario(objc ,this,false,loginActual);
        editar.setVisible(true);
    }//GEN-LAST:event_botonEditarPerfilUsuarioActionPerformed

    public void obtenerObjetosRemotos(){      
        autenticacion = (autenticacionUsuario) objc.ObtenerServant("ServantAuten");
        gestion = (Interfaz_Gestion) objc.ObtenerServant("ServantGest");
        admin = (Interfaz_Administrador) objc.ObtenerServant("ServantAdmin");     
    }
    
    public void actualizarListaRegistrados(){
        System.out.println("Actualizando Registrados");
        DefaultListModel modelo = new DefaultListModel();
        Usuario[] usuarios = gestion.consultarUsuarios();
        if(usuarios.length != 0){
            for(Usuario usuario: usuarios){
                modelo.addElement(usuario.getLoginUsuario());
            }
        }else{
            modelo.addElement("No hay usuarios registrados");
        }
        
        this.listaRegistrados.setModel(modelo);
    }
    
    public void actualizarListaSuscritos(){
        System.out.println("Actualizando suscritos");
        DefaultListModel modelo = new DefaultListModel();
        String[] usuarios = admin.obtenerSuscritos();
        if(usuarios.length != 0){
            for(String usuario: usuarios){
                modelo.addElement(usuario);
            }
        }else{
            modelo.addElement("No hay usuarios suscritos");
        }
        this.listaConectados.setModel(modelo);
    }
    
    public void actualizarPanelInfoUsuario(Usuario u){
        System.out.println("Actualizando datos del panel");
        this.campoNombre.setText(u.getNombresUsuario());
        this.campoApellidos.setText(u.getApellidosUsuario());
        this.campoLogin.setText(u.getLoginUsuario());
        if(u.desactivado){
            /*Esta desactivado, se muestra el campo estado como inactivo*/
            this.campoEstado.setText("Inactivo");
            this.botonDesactivar.setText("Activar");
        }else{
            /*Esta activado, se muestra el campo estado como activo*/
            this.campoEstado.setText("Activo");
            this.botonDesactivar.setText("Desactivar");
        }
    }
    
    public void limpiarPanelInfoUsuario(){
        this.campoNombre.setText("");
        this.campoApellidos.setText("");
        this.campoLogin.setText("");
    }
    
    public void actualizarLogin(String login){
        this.usuarioIniciado.setText(login);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard("Usuario").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraPrograma;
    private javax.swing.JPanel ContenedorDatosSesion;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JLabel botonCerrar;
    private javax.swing.JLabel botonCerrarSesion;
    private javax.swing.JButton botonDesactivar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEditarPerfilUsuario;
    private javax.swing.JButton botonEliminarSuscripcion;
    private javax.swing.JLabel botonPausa;
    private javax.swing.JLabel botonReproducir;
    private java.awt.Button botonSelecionarCancion;
    private javax.swing.JButton botonSuscribirme;
    private javax.swing.JLabel campoApellidos;
    private javax.swing.JLabel campoEstado;
    private javax.swing.JLabel campoLogin;
    private javax.swing.JLabel campoNombre;
    private javax.swing.JPanel contenedorBienvenida;
    private javax.swing.JPanel contenedorBienvenidaCliente;
    private javax.swing.JPanel contenedorGeneral;
    private javax.swing.JPanel contenedorInfoUsuario;
    private javax.swing.JTabbedPane contenedorPaneles;
    private javax.swing.JPanel contenedorReproductor;
    private javax.swing.JPanel contenedorReproductorCliente;
    private javax.swing.JPanel contenedorSuscripcion;
    private javax.swing.JPanel contenedorUsuariosConectados;
    private javax.swing.JPanel contenedorUsuariosRegistrados;
    private javax.swing.JLabel estadoSuscripcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> listaConectados;
    private javax.swing.JList<String> listaRegistrados;
    private javax.swing.JLabel nombreCancion;
    private javax.swing.JLabel nombreCancion1;
    private javax.swing.JTextArea textoBienvenida;
    private javax.swing.JTextArea textoBienvenida1;
    private javax.swing.JLabel tituloApp;
    private javax.swing.JLabel usuarioIniciado;
    // End of variables declaration//GEN-END:variables
}
