package sop_corba.Interfaz_UsuarioPackage;


/**
* sop_corba/Interfaz_UsuarioPackage/audioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* jueves 1 de junio de 2017 11:29:38 AM COT
*/

public final class audioHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public audioHolder ()
  {
  }

  public audioHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.Interfaz_UsuarioPackage.audioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.Interfaz_UsuarioPackage.audioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.Interfaz_UsuarioPackage.audioHelper.type ();
  }

}
