package sop_corba.Interfaz_GestionPackage;


/**
* sop_corba/Interfaz_GestionPackage/ListUsuariosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/HP/Desktop/Musica_CORBA/interface.idl
* sábado 10 de junio de 2017 12:13:27 PM COT
*/

public final class ListUsuariosHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.Usuario value[] = null;

  public ListUsuariosHolder ()
  {
  }

  public ListUsuariosHolder (sop_corba.Usuario[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.Interfaz_GestionPackage.ListUsuariosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.Interfaz_GestionPackage.ListUsuariosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.Interfaz_GestionPackage.ListUsuariosHelper.type ();
  }

}
